name: Prepare build information
description: Prepare build information

outputs:
  build_id:
    description: |-
      The image digest of the generated docker image
    value: "build_id"
  build_pipeline_id:
    description: |-
      The image tag of the generated docker image
    value: "build_pipeline_id"
  build_commit_sha:
    description: |-
      The image tag of the generated docker image
    value: "build_commit_sha"

runs:
  using: "composite"
  steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

    # Determine the build information for the docker image
    - name: Retrieve build information from Pull Request
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: |
        echo "LAST_COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> ${GITHUB_ENV}
        echo "BUILD_PIPELINE=${{ github.run_id }}" >> ${GITHUB_ENV}
        echo "BUILD_BRANCH=${{ github.ref_name }}" >> ${GITHUB_ENV}

    #
    - name: Retrieve build information from Push
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: |
        echo "LAST_COMMIT_SHA=${GITHUB_SHA}" >> ${GITHUB_ENV}
        echo "BUILD_PIPELINE=${{ github.run_id }}" >> ${GITHUB_ENV}
        echo "BUILD_BRANCH=${{ github.ref_name }}" >> ${GITHUB_ENV}
