name: Build ubuntu images

on:
  push:
    paths:
      - ".github/workflows/build.yml"
    branches:
      - "main"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
  workflow_dispatch:

env:
  SLUG: ${{ github.repository_owner }}/ubuntu
  PUSH_GHCR: ${{ github.repository == (github.event.pull_request.head.repo.full_name || github.repository) && '1' || '' }}

defaults:
  run:
    shell: sh

jobs:
  build:
    name: Build base ${{ matrix.TAG }}
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: Docker meta
        if: ${{ github.actor != 'nektos/act' }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: name/app

      - name: HelloWorld
        env:
          METADATA: ${{ toJSON(github) }}
        run: echo "Hello World=${METADATA}"
