name: Code Quality

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: sh

jobs:
  test:
    name: Unit Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run Unit Tests
        run: |
          pnpm -w run test

  lint:
    name: Linting
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install

      - name: Code checking
        run: |
          pnpm -w run lint
