name: Demo

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: sh

jobs:
  test:
    name: Test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install

      - name: Create docker image for 'services/payment-service'
        id: docker-create
        uses: ./.github/actions/create-docker-image
        with:
          workspace_name: payment-service
          workspace_directory: services/payment-service
          port: 30001
          dockerfile: Dockerfile
          #
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          CI_JOB_TOKEN: ${{ secrets.CI_JOB_TOKEN }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(steps.docker-create) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - id: deploy_image
        name: Deploy docker image
        shell: sh
        run: |
          docker push ${{ steps.docker-create.outputs.image_tag }}
