name: Experiment

on:
  push:
  pull_request:

defaults:
  run:
    shell: sh

jobs:
  test:
    name: Sanity Test
    timeout-minutes: 60
    runs-on: ubuntu-latest

    #
    services:
      # Redis
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --name redis
      # Cloud PubSub emulator
      pubsub:
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
        ports:
          - "8085:8085"
        options: >-
          --name pubsub
      # Postgres
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --name postgres
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - uses: pnpm/action-setup@v2.4.0
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install

      - name: Generate developer certificates
        run: |
          echo "::group::Prepare"
          sudo apt update
          sudo apt install -y libnss3-tools
          wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64
          mv mkcert-v1.4.3-linux-amd64 ./tools/mkcert
          chmod +x ./tools/mkcert
          ./tools/mkcert --version
          echo "::endgroup::"
          echo "::group::Create certificates"
          CAROOT=./ssl ./tools/mkcert -key-file ./ssl/localhost-key.pem -cert-file ./ssl/localhost.pem "*.example.com" example.test localhost 127.0.0.1 ::1
          CAROOT=./ssl ./tools/mkcert -install
          echo "::endgroup::"
          echo "::group::Generated certificates"
          ls -la ssl
          sudo update-ca-certificates --fresh
          echo "::endgroup::"

      - name: Install Playwright dependencies
        run: |
          pnpm dlx playwright install --with-deps

      - name: Run Tests
        run: |
          pnpm --filter="system-tests" run test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: integration-tests/system-tests/reporters/
          retention-days: 30
