name: Next App

on:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell: sh

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      workspace_name: next-app
      workspace_directory: projects/next-app
      service_port: 3000
      dockerfile: Dockerfile
    secrets: inherit
