name: Pull request

on:
  pull_request:

jobs:
  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run
        shell: sh
        run: echo "Code has been checked out for pull request"
