name: Quality Assurance

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: sh

jobs:
  test:
    name: System Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm --filter="system-tests" run test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: integration-tests/system-tests/reporters/
          retention-days: 30
