name: Quality Assurance

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: sh

jobs:
  test:
    name: System Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install
          pnpm dlx playwright install --with-deps

      - name: Generate developer certificates
        run: |
          pnpm add -g mkcert
          CAROOT=./ssl pnpm exec mkcert -key-file ./ssl/localhost-key.pem -cert-file ./ssl/localhost-cert.pem "*.example.com" example.test localhost 127.0.0.1 ::1

      - name: Run Tests
        env:
          NODE_EXTRA_CA_CERTS: ".ssl/rootCA.pem"
        run: |
          pnpm --filter="system-tests" run test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: integration-tests/system-tests/reporters/
          retention-days: 30
