name: Quality Assurance

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: sh

jobs:
  qa:
    name: System Tests
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: HelloWorld
        run: echo "Hello World"
