name: Release

on:
  workflow_call:
    inputs:
      workspace_name:
        description: "Workspace"
        required: true
        type: string
      workspace_directory:
        description: "Workspace Directory"
        required: true
        type: string
      service_port:
        description: "Port"
        required: true
        default: 3000
        type: number
      dockerfile:
        description: "Dockerfile"
        default: "Dockerfile"
        required: true
        type: string

jobs:
  changed_files:
    name: Verify if '${{ inputs.workspace_name }}' needs to be build
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

  build:
    name: Building docker image
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: changed_files

    steps:
      # Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
