name: Release

on:
  workflow_call:
    inputs:
      workspace_name:
        description: "Workspace"
        required: true
        type: string
      workspace_directory:
        description: "Workspace Directory"
        required: true
        type: string
      service_port:
        description: "Port"
        required: true
        default: 3000
        type: number
      dockerfile:
        description: "Dockerfile"
        default: "Dockerfile"
        required: true
        type: string

jobs:
  build:
    name: Building docker image
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create docker image for '${{ inputs.workspace_name }}'
        id: docker-create
        uses: ./.github/actions/create-docker-image
        with:
          workspace_name: ${{ inputs.workspace_name }}
          workspace_directory: ${{ inputs.workspace_directory }}
          port: ${{ inputs.service_port }}
          dockerfile: ${{ inputs.dockerfile }}
