name: Secret scanning

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.62.1
        with:
          path: ./
          extra_args: --debug
