name: Stepping Stone

on:
  workflow_call:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Quality Assurance"]
    types:
      - completed

defaults:
  run:
    shell: sh

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.changes.outputs.packages }}
      package_names: ${{ steps.changes.outputs.package_names }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Collect Turborepo Changes
        id: changes
        uses: ./.github/actions/turborepo-changes
        with:
          from: HEAD^1

  #
  webhooks-service:
    needs: [prepare]
    if: contains(fromJson(needs.prepare.outputs.package_names), 'webhooks-service')
    uses: ./.github/workflows/webhook-service.yml
    secrets: inherit

  #
  payment-service:
    needs: [prepare]
    if: contains(fromJson(needs.prepare.outputs.package_names), 'payment-service')
    uses: ./.github/workflows/webhook-service.yml
    secrets: inherit

  #
  next-app:
    needs: [prepare]
    if: contains(fromJson(needs.prepare.outputs.package_names), 'next-app')
    uses: ./.github/workflows/next-app.yml
    secrets: inherit
