name: Stepping Stone

on:
  workflow_call:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Quality Assurance"]
    types:
      - completed

defaults:
  run:
    shell: sh

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessary for comparing changes to past commits

      - name: Collect Turborepo Changes
        id: changes
        uses: ./.github/actions/turborepo-changes
        with:
          from: HEAD^1 # Changes since previous commit (this is the default)

      - name: Dump context
        env:
          STEP_CONTEXT: ${{ toJson(steps.changes) }}
        run: |
          echo "$STEP_CONTEXT"

  trigger:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Trigger 1
        run: |
          echo "Hello this is the preflight task"
      - name: Trigger 2
        run: |
          echo "Hello this is the preflight task"
      - name: Trigger 3
        run: |
          echo "Hello this is the preflight task"
