name: Stepping Stone

on:
  workflow_call:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Quality Assurance"]
    types:
      - completed

defaults:
  run:
    shell: sh

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.changes.outputs.packages }}
      package_names: ${{ steps.changes.outputs.package_names }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #
      - name: Collect Turborepo Changes
        id: changes
        uses: ./.github/actions/turborepo-changes
        with:
          from: HEAD^1

      #
      - name: Dump context
        env:
          STEP_CONTEXT: ${{ toJson(steps.changes) }}
        run: |
          echo "$STEP_CONTEXT"

  trigger:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: "@weyert/environment"
        if: contains(fromJson(needs.prepare.outputs.package_names), '@weyert/environment')
        run: |
          echo "Hello this is the preflight task"

      - name: Next App
        if: contains(fromJson(needs.prepare.outputs.package_names), 'next-app')
        run: |
          echo "Hello this is the preflight task"

      - name: Payment Service
        if: contains(fromJson(needs.prepare.outputs.package_names), 'payment-service')
        run: |
          echo "Hello this is the preflight task"

      - name: Webhooks Service
        if: contains(fromJson(needs.prepare.outputs.package_names), 'webhooks-service')
        run: |
          echo "Hello this is the preflight task"
