name: Webhook Service

on:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell: sh

jobs:
  deploy:
    uses: ./.github/workflows/release.yml
    with:
      workspace_name: webhooks-service
      workspace_directory: services/webhooks-mock-service
      service_port: 30001
      dockerfile: Dockerfile
    secrets: inherit
