name: Webhook Service

on:
  #
  workflow_dispatch:
  workflow_call:
  #
  pull_request:

defaults:
  run:
    shell: sh

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      workspace_name: webhooks-service
      workspace_directory: services/webhooks-mock-service
      service_port: 30001
      dockerfile: Dockerfile
    secrets: inherit

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkpoint
        run: |
          echo "Checkpoint for the release job"
