name: Webhook Service

on:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell: sh

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      workspace_name: webhooks-service
      workspace_directory: services/webhooks-mock-service
      service_port: 30001
      dockerfile: Dockerfile
    secrets: inherit
